<?php
// This is a complete copy of integrations-config.php with ALL fields added
// Save this when done and replace the original

if (!defined('ABSPATH'))
    exit;

function serc_get_integrations_config()
{
    return [
        'cpf' => [
            ['id' => 'cpf', 'name' => 'CPF Básico', 'description' => 'Consulta básica de CPF com dados cadastrais', 'shortcode' => 'serc_cpf_form', 'value' => '5,50', 'type' => 'Requisição', 'icon' => 'ph-identification-card', 'fields' => [['name' => 'cpf', 'label' => 'CPF', 'placeholder' => '000.000.000-00', 'type' => 'text', 'required' => true, 'class' => 'cpf']]],
            ['id' => 'cpf_renda', 'name' => 'CPF com Renda', 'description' => 'Consulta CPF incluindo informações de renda', 'shortcode' => 'serc_cpf_renda_form', 'value' => '8,90', 'type' => 'Requisição', 'icon' => 'ph-currency-circle-dollar', 'fields' => [['name' => 'cpf', 'label' => 'CPF', 'placeholder' => '000.000.000-00', 'type' => 'text', 'required' => true, 'class' => 'cpf']]],
            ['id' => 'serasa_premium', 'name' => 'Serasa Premium', 'description' => 'Consulta completa Serasa com score e histórico', 'shortcode' => 'serc_serasa_premium_form', 'value' => '22,00', 'type' => 'Requisição', 'icon' => 'ph-star', 'fields' => [['name' => 'cpf', 'label' => 'CPF', 'placeholder' => '000.000.000-00', 'type' => 'text', 'required' => true, 'class' => 'cpf']]],
            ['id' => 'ic_basico_score', 'name' => 'IC Básico Score', 'description' => 'Informações cadastrais básicas com score', 'shortcode' => 'serc_ic_basico_score_form', 'value' => '12,50', 'type' => 'Requisição', 'icon' => 'ph-chart-line', 'fields' => [['name' => 'cpf', 'label' => 'CPF', 'placeholder' => '000.000.000-00', 'type' => 'text', 'required' => true, 'class' => 'cpf']]],
            ['id' => 'scpc_bv_plus', 'name' => 'SCPC Boa Vista Plus', 'description' => 'Consulta SCPC Boa Vista versão premium', 'shortcode' => 'serc_scpc_bv_plus_v2_form', 'value' => '17,89', 'type' => 'Requisição', 'icon' => 'ph-shield-check', 'fields' => [['name' => 'cpf', 'label' => 'CPF', 'placeholder' => '000.000.000-00', 'type' => 'text', 'required' => true, 'class' => 'cpf']]],
            ['id' => 'srs_premium', 'name' => 'SRS Premium', 'description' => 'Sistema de Risco Serasa Premium', 'shortcode' => 'serc_srs_premium_form', 'value' => '19,90', 'type' => 'Requisição', 'icon' => 'ph-shield-star', 'fields' => [['name' => 'cpf', 'label' => 'CPF', 'placeholder' => '000.000.000-00', 'type' => 'text', 'required' => true, 'class' => 'cpf']]],
            ['id' => 'scpc_boa_vista', 'name' => 'SCPC Boa Vista', 'description' => 'Verificação de restrições SCPC', 'shortcode' => 'serc_scpc_boa_vista_form', 'value' => '12,50', 'type' => 'Requisição', 'icon' => 'ph-shield', 'fields' => [['name' => 'cpf', 'label' => 'CPF', 'placeholder' => '000.000.000-00', 'type' => 'text', 'required' => true, 'class' => 'cpf']]],
            ['id' => 'bacen', 'name' => 'BACEN', 'description' => 'Consulta Sistema de Informações de Crédito', 'shortcode' => 'serc_bacen_form', 'value' => '15,00', 'type' => 'Requisição', 'icon' => 'ph-bank', 'fields' => [['name' => 'cpf', 'label' => 'CPF', 'placeholder' => '000.000.000-00', 'type' => 'text', 'required' => true, 'class' => 'cpf']]],
            ['id' => 'quod', 'name' => 'QUOD', 'description' => 'Consulta bureau de crédito QUOD', 'shortcode' => 'serc_quod_form', 'value' => '14,50', 'type' => 'Requisição', 'icon' => 'ph-coin', 'fields' => [['name' => 'cpf', 'label' => 'CPF', 'placeholder' => '000.000.000-00', 'type' => 'text', 'required' => true, 'class' => 'cpf']]],
            ['id' => 'spc_brasil_cenprot', 'name' => 'SPC Brasil CENPROT', 'description' => 'Consulta SPC com dados CENPROT', 'shortcode' => 'serc_spc_brasil_cenprot_form', 'value' => '13,00', 'type' => 'Requisição', 'icon' => 'ph-list-checks', 'fields' => [['name' => 'cpf', 'label' => 'CPF', 'placeholder' => '000.000.000-00', 'type' => 'text', 'required' => true, 'class' => 'cpf']]],
            ['id' => 'spc_brasil_serasa', 'name' => 'SPC Brasil Serasa', 'description' => 'Consulta SPC com dados Serasa', 'shortcode' => 'serc_spc_brasil_serasa_form', 'value' => '16,00', 'type' => 'Requisição', 'icon' => 'ph-list-star', 'fields' => [['name' => 'cpf', 'label' => 'CPF', 'placeholder' => '000.000.000-00', 'type' => 'text', 'required' => true, 'class' => 'cpf']]],
            ['id' => 'dividas_bancarias', 'name' => 'Dívidas Bancárias', 'description' => 'Consulta de dívidas bancárias por CPF', 'shortcode' => 'serc_dividas_bancrias_cpf_form', 'value' => '11,00', 'type' => 'Requisição', 'icon' => 'ph-warning-circle', 'fields' => [['name' => 'cpf', 'label' => 'CPF', 'placeholder' => '000.000.000-00', 'type' => 'text', 'required' => true, 'class' => 'cpf']]],
            ['id' => 'cadastrais_score_dividas', 'name' => 'Cadastrais Score Dívidas', 'description' => 'Dados cadastrais com score e dívidas', 'shortcode' => 'serc_cadastrais_score_dividas_form', 'value' => '18,50', 'type' => 'Requisição', 'icon' => 'ph-user-circle-check', 'fields' => [['name' => 'cpf', 'label' => 'CPF', 'placeholder' => '000.000.000-00', 'type' => 'text', 'required' => true, 'class' => 'cpf']]],
            ['id' => 'scr_bacen_score', 'name' => 'SCR BACEN Score', 'description' => 'Sistema de Informações de Crédito com score', 'shortcode' => 'serc_scr_bacen_score_form', 'value' => '20,00', 'type' => 'Requisição', 'icon' => 'ph-chart-bar', 'fields' => [['name' => 'cpf', 'label' => 'CPF', 'placeholder' => '000.000.000-00', 'type' => 'text', 'required' => true, 'class' => 'cpf']]],
            ['id' => 'ic_nome', 'name' => 'IC por Nome', 'description' => 'Informações cadastrais por nome completo', 'shortcode' => 'serc_ic_nome_form', 'value' => '7,50', 'type' => 'Requisição', 'icon' => 'ph-user-list', 'fields' => [['name' => 'name', 'label' => 'Nome completo', 'placeholder' => 'Nome completo', 'type' => 'text', 'required' => true], ['name' => 'state', 'label' => 'UF', 'placeholder' => 'SP', 'type' => 'text', 'required' => true]]],
            ['id' => 'ic_telefone', 'name' => 'IC por Telefone', 'description' => 'Informações cadastrais por telefone', 'shortcode' => 'serc_ic_telefone_form', 'value' => '6,90', 'type' => 'Requisição', 'icon' => 'ph-phone', 'fields' => [['name' => 'ddd', 'label' => 'DDD', 'placeholder' => '11', 'type' => 'text', 'required' => true], ['name' => 'telefone', 'label' => 'Telefone', 'placeholder' => '999999999', 'type' => 'text', 'required' => true], ['name' => 'state', 'label' => 'UF', 'placeholder' => 'SP', 'type' => 'text', 'required' => true]]],
            ['id' => 'ic_cnh', 'name' => 'IC CNH', 'description' => 'Informações de CNH por CPF', 'shortcode' => 'serc_ic_cnh_form', 'value' => '9,50', 'type' => 'Requisição', 'icon' => 'ph-identification-badge', 'fields' => [['name' => 'cpf', 'label' => 'CPF', 'placeholder' => '000.000.000-00', 'type' => 'text', 'required' => true, 'class' => 'cpf']]],
        ],
        'cnpj' => [
            ['id' => 'cnpj', 'name' => 'CNPJ Básico', 'description' => 'Consulta básica de CNPJ com dados cadastrais', 'shortcode' => 'serc_cnpj_form', 'value' => '10,00', 'type' => 'Requisição', 'icon' => 'ph-buildings', 'fields' => [['name' => 'cnpj', 'label' => 'CNPJ', 'placeholder' => '00.000.000/0000-00', 'type' => 'text', 'required' => true, 'class' => 'cnpj']]],
            ['id' => 'bin_estadual', 'name' => 'BIN Estadual', 'description' => 'Base de Inadimplentes Estadual', 'shortcode' => 'serc_bin_estadual_form', 'value' => '12,00', 'type' => 'Requisição', 'icon' => 'ph-warning', 'fields' => [['name' => 'estado', 'label' => 'UF', 'placeholder' => 'SP', 'type' => 'text', 'required' => true]]],
            ['id' => 'bin_nacional', 'name' => 'BIN Nacional', 'description' => 'Base de Inadimplentes Nacional por CPF', 'shortcode' => 'serc_bin_nacional_form', 'value' => '14,00', 'type' => 'Requisição', 'icon' => 'ph-warning-octagon', 'fields' => [['name' => 'cpf', 'label' => 'CPF', 'placeholder' => '000.000.000-00', 'type' => 'text', 'required' => true, 'class' => 'cpf']]],
        ],
        'veicular' => [
            ['id' => 'ic_placa', 'name' => 'Consulta por Placa', 'description' => 'Informações cadastrais veiculares por placa', 'shortcode' => 'serc_ic_placa_form', 'value' => '8,50', 'type' => 'Requisição', 'icon' => 'ph-car', 'fields' => [['name' => 'placa', 'label' => 'Placa', 'placeholder' => 'ABC1D23', 'type' => 'text', 'required' => true]]],
            ['id' => 'crlv', 'name' => 'CRLV', 'description' => 'Certificado de Registro e Licenciamento', 'shortcode' => 'serc_crlv_form', 'value' => '12,00', 'type' => 'Requisição', 'icon' => 'ph-file-text', 'fields' => [['name' => 'placa', 'label' => 'Placa', 'placeholder' => 'ABC1D23', 'type' => 'text', 'required' => true]]],
            ['id' => 'renainf', 'name' => 'RENAINF', 'description' => 'Registro Nacional de Infrações de Trânsito', 'shortcode' => 'serc_renainf_form', 'value' => '10,50', 'type' => 'Requisição', 'icon' => 'ph-traffic-sign', 'fields' => [['name' => 'placa', 'label' => 'Placa', 'placeholder' => 'ABC1D23', 'type' => 'text', 'required' => true], ['name' => 'renavam', 'label' => 'RENAVAM', 'placeholder' => '00000000000', 'type' => 'text', 'required' => true]]],
            ['id' => 'gravame', 'name' => 'Gravame', 'description' => 'Consulta de gravame por chassi', 'shortcode' => 'serc_gravame_form', 'value' => '9,00', 'type' => 'Requisição', 'icon' => 'ph-seal', 'fields' => [['name' => 'chassi', 'label' => 'Chassi', 'placeholder' => '17 caracteres', 'type' => 'text', 'required' => true]]],
            ['id' => 'laudo_veicular', 'name' => 'Laudo Veicular', 'description' => 'Laudo completo do veículo', 'shortcode' => 'serc_laudo_veicular_form', 'value' => '25,00', 'type' => 'Requisição', 'icon' => 'ph-file-doc', 'fields' => [['name' => 'placa', 'label' => 'Placa (opcional)', 'placeholder' => 'ABC1D23', 'type' => 'text', 'required' => false], ['name' => 'chassi', 'label' => 'Chassi (opcional)', 'placeholder' => '17 caracteres', 'type' => 'text', 'required' => false]]],
            ['id' => 'proprietario_placa', 'name' => 'Proprietário por Placa', 'description' => 'Dados do proprietário através da placa', 'shortcode' => 'serc_proprietario_placa_form', 'value' => '15,00', 'type' => 'Requisição', 'icon' => 'ph-user-circle', 'fields' => [['name' => 'placa', 'label' => 'Placa', 'placeholder' => 'ABC1D23', 'type' => 'text', 'required' => true]]],
            ['id' => 'foto_leilao', 'name' => 'Foto Leilão', 'description' => 'Fotos de veículos em leilão', 'shortcode' => 'serc_foto_leilao_form', 'value' => '5,00', 'type' => 'Requisição', 'icon' => 'ph-image', 'fields' => [['name' => 'leilaoId', 'label' => 'ID do Leilão', 'placeholder' => '12345', 'type' => 'text', 'required' => true]]],
            ['id' => 'leilao', 'name' => 'Leilão', 'description' => 'Consulta de veículos em leilão', 'shortcode' => 'serc_leilao_form', 'value' => '8,00', 'type' => 'Requisição', 'icon' => 'ph-gavel', 'fields' => [['name' => 'filtro', 'label' => 'Filtro', 'placeholder' => 'Filtro de busca', 'type' => 'text', 'required' => true]]],
            ['id' => 'leilao_score', 'name' => 'Leilão Score Perda Total', 'description' => 'Score de perda total para veículos leiloados', 'shortcode' => 'serc_leilao_score_perda_total_form', 'value' => '12,00', 'type' => 'Requisição', 'icon' => 'ph-fire', 'fields' => [['name' => 'placa', 'label' => 'Placa', 'placeholder' => 'ABC1D23', 'type' => 'text', 'required' => true]]],
            ['id' => 'historico_roubo', 'name' => 'Histórico Roubo/Furto', 'description' => 'Histórico de roubo e furto do veículo', 'shortcode' => 'serc_historico_roubo_furto_form', 'value' => '11,00', 'type' => 'Requisição', 'icon' => 'ph-shield-warning', 'fields' => [['name' => 'placa', 'label' => 'Placa', 'placeholder' => 'ABC1D23', 'type' => 'text', 'required' => true]]],
            ['id' => 'indice_risco', 'name' => 'Índice de Risco Veicular', 'description' => 'Índice de risco para veículos', 'shortcode' => 'serc_indice_risco_veicular_form', 'value' => '13,50', 'type' => 'Requisição', 'icon' => 'ph-warning-diamond', 'fields' => [['name' => 'placa', 'label' => 'Placa', 'placeholder' => 'ABC1D23', 'type' => 'text', 'required' => true]]],
            ['id' => 'licenciamento_anterior', 'name' => 'Licenciamento Anterior', 'description' => 'Histórico de licenciamento', 'shortcode' => 'serc_licenciamento_anterior_form', 'value' => '7,00', 'type' => 'Requisição', 'icon' => 'ph-calendar-check', 'fields' => [['name' => 'placa', 'label' => 'Placa', 'placeholder' => 'ABC1D23', 'type' => 'text', 'required' => true]]],
            ['id' => 'proprietario_atual', 'name' => 'Proprietário Atual', 'description' => 'Dados do proprietário atual', 'shortcode' => 'serc_ic_proprietario_atual_form', 'value' => '14,00', 'type' => 'Requisição', 'icon' => 'ph-user-focus', 'fields' => [['name' => 'placa', 'label' => 'Placa', 'placeholder' => 'ABC1D23', 'type' => 'text', 'required' => true]]],
            ['id' => 'gravame_detalhamento', 'name' => 'Gravame Detalhado', 'description' => 'Detalhamento completo de gravames', 'shortcode' => 'serc_gravame_detalhamento_form', 'value' => '16,00', 'type' => 'Requisição', 'icon' => 'ph-seal-check', 'fields' => [['name' => 'placa', 'label' => 'Placa', 'placeholder' => 'ABC1D23', 'type' => 'text', 'required' => true]]],
            ['id' => 'renajud', 'name' => 'RENAJUD', 'description' => 'Registro Nacional de Restrições Judiciais', 'shortcode' => 'serc_renajud_form', 'value' => '10,00', 'type' => 'Requisição', 'icon' => 'ph-scales', 'fields' => [['name' => 'placa', 'label' => 'Placa', 'placeholder' => 'ABC1D23', 'type' => 'text', 'required' => true]]],
            ['id' => 'renainf_placa', 'name' => 'RENAINF por Placa', 'description' => 'Infrações por placa', 'shortcode' => 'serc_renainf_placa_form', 'value' => '9,50', 'type' => 'Requisição', 'icon' => 'ph-traffic-cone', 'fields' => [['name' => 'placa', 'label' => 'Placa', 'placeholder' => 'ABC1D23', 'type' => 'text', 'required' => true]]],
            ['id' => 'fipe', 'name' => 'Tabela FIPE', 'description' => 'Preço FIPE do veículo', 'shortcode' => 'serc_fipe_form', 'value' => '3,00', 'type' => 'Requisição', 'icon' => 'ph-tag', 'fields' => [['name' => 'marca', 'label' => 'Marca', 'placeholder' => 'Marca', 'type' => 'text', 'required' => true], ['name' => 'modelo', 'label' => 'Modelo', 'placeholder' => 'Modelo', 'type' => 'text', 'required' => true], ['name' => 'ano', 'label' => 'Ano', 'placeholder' => '2024', 'type' => 'text', 'required' => true]]],
            ['id' => 'sinistro', 'name' => 'Sinistro', 'description' => 'Histórico de sinistros', 'shortcode' => 'serc_sinistro_form', 'value' => '12,50', 'type' => 'Requisição', 'icon' => 'ph-first-aid', 'fields' => [['name' => 'placa', 'label' => 'Placa', 'placeholder' => 'ABC1D23', 'type' => 'text', 'required' => true]]],
            ['id' => 'recall', 'name' => 'Recall', 'description' => 'Consulta de recalls por modelo', 'shortcode' => 'serc_recall_form', 'value' => '4,50', 'type' => 'Requisição', 'icon' => 'ph-wrench', 'fields' => [['name' => 'modelo', 'label' => 'Modelo', 'placeholder' => 'Modelo do veículo', 'type' => 'text', 'required' => true]]],
        ],
        'juridico' => [
            ['id' => 'dossie_juridico', 'name' => 'Dossiê Jurídico', 'description' => 'Dossiê completo jurídico CPF/CNPJ', 'shortcode' => 'serc_dossie_juridico_form', 'value' => '35,00', 'type' => 'Requisição', 'icon' => 'ph-folder-open', 'fields' => [['name' => 'document', 'label' => 'CPF ou CNPJ', 'placeholder' => 'Digite CPF ou CNPJ', 'type' => 'text', 'required' => true]]],
            ['id' => 'protesto_nacional', 'name' => 'Protesto Nacional CENPROT', 'description' => 'Consulta de protestos nacionais', 'shortcode' => 'serc_protesto_nacional_cenprot_form', 'value' => '15,00', 'type' => 'Requisição', 'icon' => 'ph-warning', 'fields' => [['name' => 'cpf', 'label' => 'CPF', 'placeholder' => '000.000.000-00', 'type' => 'text', 'required' => true, 'class' => 'cpf']]],
            ['id' => 'acoes_processos', 'name' => 'Ações e Processos Judiciais', 'description' => 'Consulta de ações e processos', 'shortcode' => 'serc_r_acoes_e_processos_judiciais_form', 'value' => '28,00', 'type' => 'Requisição', 'icon' => 'ph-gavel', 'fields' => [['name' => 'cpf', 'label' => 'CPF', 'placeholder' => '000.000.000-00', 'type' => 'text', 'required' => true, 'class' => 'cpf']]],
            ['id' => 'dossie_juridico_cpf', 'name' => 'Dossiê Jurídico CPF', 'description' => 'Dossiê jurídico específico para CPF', 'shortcode' => 'serc_dossie_juridico_cpf_form', 'value' => '32,00', 'type' => 'Requisição', 'icon' => 'ph-file-magnifying-glass', 'fields' => [['name' => 'cpf', 'label' => 'CPF', 'placeholder' => '000.000.000-00', 'type' => 'text', 'required' => true, 'class' => 'cpf']]],
            ['id' => 'certidao_trabalhista', 'name' => 'Certidão Débitos Trabalhistas', 'description' => 'Certidão nacional de débitos trabalhistas', 'shortcode' => 'serc_certidao_nacional_debitos_trabalhistas_form', 'value' => '18,00', 'type' => 'Requisição', 'icon' => 'ph-briefcase', 'fields' => [['name' => 'cpf', 'label' => 'CPF', 'placeholder' => '000.000.000-00', 'type' => 'text', 'required' => true, 'class' => 'cpf']]],
        ]
    ];
}

function serc_get_category_integrations($category)
{
    $all = serc_get_integrations_config();
    return $all[$category] ?? [];
}

function serc_get_integration_by_id($integration_id)
{
    $all = serc_get_integrations_config();
    foreach ($all as $category => $integrations) {
        foreach ($integrations as $integration) {
            if ($integration['id'] === $integration_id) {
                return $integration;
            }
        }
    }
    return null;
}
